@startuml

actor "Клієнтська програма" as Program

participant "Client" as Client
participant "QueryBuilder" as QB
participant "MSSQLAdapter" as Adapter
database "MSSQL Database" as DB

Program -> Client : Створення клієнта(CreateClient)
Client -> Adapter : Передача аргументів клієнта
Adapter --> Client : Отримання строки підключення
Client -> DB : Ініціалізація підключення до бази даних
DB --> Client : Отримання екземпляру підключення
Client --> Program : Отримання клієнта
@enduml

