@startuml
actor "Клієнтська програма" as Program

participant "Client" as Client
participant "QueryBuilder" as QB
participant "MSSQLAdapter" as Adapter
database "MSSQL Database" as DB

Program -> QB : Створення будівельника запитів (CreateQueryBuilder)
QB -> QB : Створення умови (Where)
QB -> QB : Доповнення умови (AndWhere)
QB -> QB : Завантаження замовлень (Preload)
QB -> QB : Завантаження ролі користувача (Preload)
QB -> QB : Сортування за ідентифікатором (OrderBy)
QB -> QB : Вказання максимальної кількості записів (Limit)
QB -> QB : Вказання пропуску перших записів (Offset)
QB -> QB : Включення логування запитів (Debug)
QB -> QB : Отримання записів (FindMany)

QB -> Adapter : Будування SQL запиту
Adapter --> QB : Отримання алгоритмів будування SQL для конкретної бази даних
QB -> Client : Надсилання SQL запиту
Client -> DB : Виконання SQL запиту
DB --> QB : Повернення даних

QB -> Adapter : Будування SQL запиту дозавантаження даних
Adapter --> QB : Отримання алгоритмів будування SQL для конкретної бази даних
QB -> Client : Надсилання SQL запиту
Client -> DB : Виконання SQL запиту
DB --> QB : Повернення даних

QB --> Program : Приведення даних до типу []User
@enduml

