@startuml
start

:Адміністратор заходить в адміністративну панель;
:Обирає таблицю бази даних;
:Сервер відкриває транзакцію;

repeat
  :Виконання операції;
repeat while (Є ще операції?) is (так)

if (Усі операції успішні?) then (так)
  :Фіксація транзакції;
  :Оновлення даних у базі;
else (ні)
  :Відкат транзакції;
  :Повідомлення про помилку;
endif

stop
@enduml