@startuml
skinparam rectangle {
  BackgroundColor white
  BorderColor black
}

' Title
title ORM

' Frontend
package "Frontend" {
  [HTMX]
}

' Admin Backend
package "Admin Backend" {
  [API (Fiber)]
  [Admin Business Logic]
}

' App Backend
package "App Backend" {
  [App (Golang)]
  [CLI (Cobra)]
  [App Business Logic]
}

' Main Database
package "Database" {
  [SQL Database\n(MySQL, PostgreSQL or SQLite)]
}

' Log Database
package "Log Database" {
  [NoSQL Database\n(Elasticsearch)]
}

' Connections
[HTMX] --> [API (Fiber)] : REST API (HTTPS)
[API (Fiber)] --> [Admin Business Logic] : TCP/IP
[Admin Business Logic] --> [SQL Database\n(MySQL, PostgreSQL or SQLite)] : TCP/IP
[Admin Business Logic] --> [NoSQL Database\n(Elasticsearch)]

[App (Golang)] --> [App Business Logic]
[CLI (Cobra)] --> [App Business Logic]
[App Business Logic] --> [SQL Database\n(MySQL, PostgreSQL or SQLite)] : TCP/IP

@enduml
