@startuml
skinparam style strictuml



' === FACTORY METHOD ===
abstract class Creator {
    +createProduct(): Product
}

class ConcreteCreatorA extends Creator {
    +createProduct(): Product
}

class ConcreteCreatorB extends Creator {
    +createProduct(): Product
}

interface Product

ConcreteCreatorA --> Product
ConcreteCreatorB --> Product

@enduml
