name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
          cache: false

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint on all modules
        run: |
          # Get all directories from go.work
          modules=$(grep -v '^#' go.work | grep '^\s*\.' | tr -d ' \t')
          
          # Run golangci-lint on each module
          for module in $modules; do
            echo "Running golangci-lint on $module"
            cd $module
            golangci-lint run --timeout=5m ./...
            cd - > /dev/null
          done